/* Generated by cbindgen - do not edit manually */

#ifndef RUST_CORE_H
#define RUST_CORE_H

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct Discarder Discarder;

typedef struct CRank {
  uint8_t value;
} CRank;

typedef struct CSuit {
  uint8_t value;
} CSuit;

typedef struct CCard {
  struct CRank rank;
  struct CSuit suit;
} CCard;

typedef struct CPokerHandsCount {
  int64_t counts[10];
} CPokerHandsCount;

typedef void (*ProgressHandler)(void *context,
                                const struct CPokerHandsCount *counts,
                                uintptr_t iterations,
                                double fraction);

struct Discarder *discarder_new(const struct CCard *deck,
                                uintptr_t deck_size,
                                uintptr_t hand_size,
                                uint64_t seed);

void discarder_free(struct Discarder *discarder);

uintptr_t discarder_run(const struct Discarder *discarder,
                        const struct CCard *hand,
                        uintptr_t hand_size,
                        uintptr_t max_iterations,
                        struct CPokerHandsCount *out_counts,
                        ProgressHandler progress_handler,
                        void *context);

#endif  /* RUST_CORE_H */
